import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import '../models/document_chunk.dart';
// Generated by: flutter pub run build_runner build
// Run that command once after the first `flutter pub get`.
import '../objectbox.g.dart';

/// Singleton service wrapping the ObjectBox [Store].
///
/// Usage:
/// ```dart
/// final obs = await ObjectBoxService.create();
/// ```
class ObjectBoxService {
  late final Store _store;
  late final Box<DocumentChunk> _box;

  ObjectBoxService._();

  /// Opens (or creates) the ObjectBox store in the app-documents directory.
  static Future<ObjectBoxService> create() async {
    final svc = ObjectBoxService._();
    final docsDir = await getApplicationDocumentsDirectory();
    final dbDir = p.join(docsDir.path, 'objectbox');
    svc._store = await openStore(directory: dbDir);
    svc._box = svc._store.box<DocumentChunk>();
    return svc;
  }

  // ───────────────────────────── Write ────────────────────────────────────

  /// Replaces the entire knowledge base with [chunks].
  Future<void> replaceChunks(List<String> chunks) async {
    _box.removeAll();
    final entities = chunks
        .where((t) => t.trim().length > 10)
        .map((t) => DocumentChunk(text: t.trim()))
        .toList();
    _box.putMany(entities);
  }

  /// Cleans raw extracted text by stripping markdown artifacts, normalizing
  /// whitespace, and removing common PDF extraction noise.
  String _sanitizeText(String text) {
    var t = text;

    // 0. Normalize PDF-specific artifacts first
    // Smart quotes → plain quotes (PDFs often use these)
    t = t.replaceAll('\u201C', '"').replaceAll('\u201D', '"');  // " "
    t = t.replaceAll('\u2018', "'").replaceAll('\u2019', "'");  // ' '
    // Non-breaking spaces → regular spaces
    t = t.replaceAll('\u00A0', ' ');
    // Common ligatures from PDF text extraction
    t = t.replaceAll('\uFB01', 'fi').replaceAll('\uFB02', 'fl');
    t = t.replaceAll('\uFB03', 'ffi').replaceAll('\uFB04', 'ffl');
    // Em/en dashes → hyphens
    t = t.replaceAll('\u2013', '-').replaceAll('\u2014', '-');
    // Ellipsis character → three dots
    t = t.replaceAll('\u2026', '...');

    // 1. Rejoin hyphenated line breaks (e.g. "con-\ntract" → "contract")
    t = t.replaceAll(RegExp(r'(\w)-\n(\w)'), r'$1$2');

    // 2. Strip markdown bold/italic markers: **text**, __text__, *text*, _text_
    //    Process longer markers first to avoid partial replacements.
    t = t.replaceAll(RegExp(r'\*{2,3}'), '');
    t = t.replaceAll(RegExp(r'_{2,3}'), '');
    // Single * or _ used as emphasis (word-bounded to avoid removing bullets)
    t = t.replaceAllMapped(
      RegExp(r'(?<=\s|^)[*_](\S(?:.*?\S)?)[*_](?=\s|$|[.,;:!?])'),
      (m) => m.group(1)!,
    );

    // 3. Strip markdown headings (# Heading → Heading)
    t = t.replaceAll(RegExp(r'^#{1,6}\s+', multiLine: true), '');

    // 4. Convert markdown links [text](url) → text
    t = t.replaceAllMapped(RegExp(r'\[([^\]]+)\]\([^)]+\)'), (m) => m.group(1)!);

    // 5. Strip markdown image references ![alt](url)
    t = t.replaceAll(RegExp(r'!\[[^\]]*\]\([^)]+\)'), '');

    // 6. Remove standalone page numbers (e.g. lines that are just "12" or "Page 12")
    t = t.replaceAll(RegExp(r'^\s*(?:Page\s*)?\d{1,4}\s*$', multiLine: true, caseSensitive: false), '');

    // 7. Normalize whitespace: collapse 3+ newlines into 2, multiple spaces into 1
    t = t.replaceAll(RegExp(r'\n{3,}'), '\n\n');
    t = t.replaceAll(RegExp(r'[^\S\n]{2,}'), ' ');

    return t.trim();
  }

  /// Smart chunking: splits raw text into semantically meaningful chunks
  /// with overlap so boundary data isn't lost.
  /// Works for any document type: legal, medical, technical, academic, etc.
  Future<void> replaceChunksFromText(String text) async {
    _box.removeAll();

    // Sanitize text before chunking: strip markdown, normalize whitespace, etc.
    final cleanText = _sanitizeText(text);

    final chunks = <String>[];

    // 1. Try splitting by common document section headers
    //    Matches numbered sections, titled headings, common structural patterns
    final sectionPattern = RegExp(
      r'(?='
      r'(?:^|\n)\s*(?:'
        r'(?:CHAPTER|SECTION|ARTICLE|PART|TITLE|SCHEDULE|ANNEX|APPENDIX|EXHIBIT|CLAUSE)\s*[\d.:IVXLC]+'
        r'|\d{1,3}(?:\.\d{1,3})*\s+[A-Z])'
      r'|(?:^|\n)\s*[A-Z][A-Z ]{4,}(?:\n|:)'
      r')',
      caseSensitive: false,
      multiLine: true,
    );
    final sections = cleanText.split(sectionPattern)
        .map((s) => s.trim())
        .where((s) => s.length > 20)
        .toList();

    if (sections.length >= 3) {
      for (final section in sections) {
        if (section.length <= 2000) {
          chunks.add(section.trim());
        } else {
          // Split oversized sections on paragraph boundaries
          final paras = section.split(RegExp(r'\n\s*\n'))
              .map((s) => s.trim())
              .where((s) => s.length > 10)
              .toList();
          String buffer = '';
          for (final para in paras) {
            if (buffer.isNotEmpty && buffer.length + para.length > 2000) {
              chunks.add(buffer.trim());
              // Overlap: keep last ~400 chars of previous chunk
              final overlap = buffer.length > 400
                  ? buffer.substring(buffer.length - 400)
                  : buffer;
              buffer = '$overlap\n\n$para';
            } else {
              buffer = buffer.isEmpty ? para : '$buffer\n\n$para';
            }
          }
          if (buffer.trim().length > 10) chunks.add(buffer.trim());
        }
      }
    }

    // 2. If section-based splitting didn't produce enough chunks, try paragraphs
    if (chunks.length < 3) {
      chunks.clear();
      final paragraphs = cleanText.split(RegExp(r'\n\s*\n'))
          .map((s) => s.trim())
          .where((s) => s.length > 20)
          .toList();

      if (paragraphs.length >= 3) {
        String buffer = '';
        for (final para in paragraphs) {
          if (buffer.isNotEmpty &&
              buffer.length + para.length > 1500 &&
              buffer.length > 200) {
            chunks.add(buffer.trim());
            // Overlap: keep last ~300 chars to preserve context across boundaries
            final overlap = buffer.length > 300
                ? buffer.substring(buffer.length - 300)
                : buffer;
            buffer = '$overlap\n\n$para';
          } else {
            buffer = buffer.isEmpty ? para : '$buffer\n\n$para';
          }
        }
        if (buffer.trim().length > 20) chunks.add(buffer.trim());
      }
    }

    // 3. Final fallback: split by sentences, grouped into ~1000-char chunks
    if (chunks.length < 3) {
      chunks.clear();
      final sentences = cleanText.split(RegExp(r'(?<=[.!?])\s+'))
          .where((s) => s.trim().length > 5)
          .toList();
      String buffer = '';
      for (final sent in sentences) {
        if (buffer.isNotEmpty &&
            buffer.length + sent.length > 1000 &&
            buffer.length > 200) {
          chunks.add(buffer.trim());
          // Overlap: keep last 2 sentences worth (~200 chars)
          final overlapStart = buffer.lastIndexOf('. ', buffer.length - 200);
          buffer = overlapStart >= 0
              ? '${buffer.substring(overlapStart + 2)} $sent'
              : sent;
        } else {
          buffer = buffer.isEmpty ? sent : '$buffer $sent';
        }
      }
      if (buffer.trim().length > 20) chunks.add(buffer.trim());
    }

    // 4. If still nothing, store the whole text as one chunk
    if (chunks.isEmpty && cleanText.length > 20) {
      chunks.add(cleanText);
    }

    // 5. Merge undersized chunks (< 200 chars) with their neighbor so we
    //    don't produce dozens of tiny fragments from short paragraphs.
    if (chunks.length > 1) {
      final merged = <String>[];
      String buffer = chunks.first;
      for (int i = 1; i < chunks.length; i++) {
        if (buffer.length < 200) {
          // Too small — merge with next chunk
          buffer = '$buffer\n\n${chunks[i]}';
        } else {
          merged.add(buffer);
          buffer = chunks[i];
        }
      }
      if (buffer.isNotEmpty) merged.add(buffer);
      chunks
        ..clear()
        ..addAll(merged);
    }

    final entities = chunks.map((t) => DocumentChunk(text: t)).toList();
    _box.putMany(entities);
  }

  /// Clears all stored chunks.
  void clearAll() => _box.removeAll();

  // ───────────────────────────── Read ──────────────────────────────────────

  // Common English stopwords to skip during keyword extraction
  static const _stopwords = {
    'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
    'should', 'may', 'might', 'shall', 'can', 'need', 'dare', 'ought',
    'used', 'to', 'of', 'in', 'for', 'on', 'with', 'at', 'by', 'from',
    'as', 'into', 'through', 'during', 'before', 'after', 'above',
    'below', 'between', 'out', 'off', 'over', 'under', 'again',
    'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why',
    'how', 'all', 'each', 'every', 'both', 'few', 'more', 'most',
    'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same',
    'so', 'than', 'too', 'very', 'just', 'because', 'but', 'and', 'or',
    'if', 'while', 'about', 'what', 'which', 'who', 'whom', 'this',
    'that', 'these', 'those', 'am', 'it', 'its', 'he', 'she', 'they',
    'them', 'his', 'her', 'my', 'your', 'our', 'their', 'me', 'him',
    'us', 'you', 'i', 'we', 'tell', 'give', 'get', 'got', 'many',
    'much', 'any', 'also', 'well', 'list', 'state', 'specific',
    'provided', 'dataset', 'levels',
  };

  // General-purpose synonym mappings for query expansion across domains.
  // Covers common conceptual groupings found in legal, medical, technical,
  // academic, and business documents.
  static const _synonyms = <String, List<String>>{
    // --- General document concepts ---
    'definition': ['defined', 'means', 'refers to', 'interpretation'],
    'obligation': ['shall', 'must', 'required', 'duty', 'responsible'],
    'prohibition': ['prohibited', 'forbidden', 'restricted', 'banned', 'unlawful'],
    'penalty': ['fine', 'punishment', 'sanction', 'damages', 'liability'],
    'agreement': ['contract', 'covenant', 'arrangement', 'undertaking'],
    'terminate': ['termination', 'cancel', 'revoke', 'rescind', 'end'],
    'compensation': ['salary', 'wages', 'remuneration', 'payment', 'pay'],
    'effective': ['commencement', 'operative', 'in force', 'enacted'],
    'amendment': ['modify', 'amend', 'revise', 'alter', 'change'],
    'liability': ['responsible', 'accountable', 'liable', 'obligation'],
    'confidential': ['proprietary', 'secret', 'non-disclosure', 'private'],
    'summary': ['overview', 'abstract', 'synopsis', 'brief'],
    'conclusion': ['finding', 'determination', 'result', 'outcome'],
    'recommendation': ['suggest', 'advise', 'propose', 'recommend'],
    'requirement': ['prerequisite', 'condition', 'criteria', 'specification'],
    'provision': ['clause', 'section', 'stipulation', 'term'],
    'author': ['writer', 'contributor', 'creator'],
    'cause': ['reason', 'basis', 'ground', 'rationale'],
    'impact': ['effect', 'consequence', 'implication', 'result'],
    // --- Medical (kept for backward compatibility) ---
    'diagnosis': ['diagnosed', 'assessment', 'impression', 'finding'],
    'medication': ['prescribed', 'drug', 'treatment', 'therapy', 'medicine'],
    'prescribed': ['medication', 'received', 'administered', 'given'],
  };

  /// Expand keywords with synonyms and prefix stems.
  /// Works across all domains (legal, medical, technical, etc.).
  List<String> _expandKeywords(List<String> keywords) {
    final expanded = <String>{...keywords};

    for (final kw in keywords) {
      // Add synonym expansions (forward lookup)
      final syns = _synonyms[kw];
      if (syns != null) expanded.addAll(syns);

      // Reverse lookup: if a synonym value is queried, also add its key
      for (final entry in _synonyms.entries) {
        if (entry.value.contains(kw)) {
          expanded.add(entry.key);
        }
      }

      // Prefix stem matching: 'prescri' matches 'prescribed', 'prescription'
      // Stems are clamped to 4-6 chars to align with _scoreChunk's prefix logic
      if (kw.length >= 6 && !kw.contains(' ')) {
        expanded.add(kw.substring(0, kw.length.clamp(4, 6)));
      }
    }

    return expanded.toList();
  }

  /// Extract keywords from a query: unigrams + bigrams + entity patterns.
  List<String> _extractKeywords(String query) {
    final keywords = <String>{};

    // 0. Extract dollar amounts and decimal numbers BEFORE cleaning
    //    e.g. "$15 million", "$2.5", "12.5%", "3.14"
    final moneyPattern = RegExp(
      r'\$\s*[\d,.]+\s*(?:million|billion|thousand|k|m|b)?'
      r'|[\d,.]+\s*(?:million|billion|thousand|percent|%)',
      caseSensitive: false,
    );
    for (final m in moneyPattern.allMatches(query)) {
      keywords.add(m.group(0)!.replaceAll(RegExp(r'\s+'), ' ').toLowerCase());
    }

    // Also preserve standalone decimal numbers like "12.5", "3.14"
    final decimalPattern = RegExp(r'\d+\.\d+');
    for (final m in decimalPattern.allMatches(query)) {
      keywords.add(m.group(0)!);
    }

    // Clean the query for general keyword extraction
    final clean = query
        .replaceAll(RegExp(r"[''`]"), ' ')
        .replaceAll(RegExp(r'[^\w\s\d()-]'), ' ');

    // Extract raw words (preserve case for entity detection)
    final rawWords = clean.split(RegExp(r'\s+'))
        .where((w) => w.length > 1)
        .toList();

    // 1. Add unigrams (lowercased, without stopwords)
    final unigrams = rawWords
        .map((w) => w.replaceAll(RegExp(r'[^\w]'), '').toLowerCase())
        .where((w) => w.length > 1 && !_stopwords.contains(w))
        .toList();
    keywords.addAll(unigrams);

    // 2. Add bigrams from consecutive non-stopword words
    //    e.g. "Thomas Wright" → "thomas wright"
    //    e.g. "serum creatinine" → "serum creatinine"
    for (int i = 0; i < rawWords.length - 1; i++) {
      final a = rawWords[i].replaceAll(RegExp(r'[^\w]'), '').toLowerCase();
      final b = rawWords[i + 1].replaceAll(RegExp(r'[^\w]'), '').toLowerCase();
      if (a.length > 1 && b.length > 1 &&
          !_stopwords.contains(a) && !_stopwords.contains(b)) {
        keywords.add('$a $b');
      }
    }

    // 3. Detect labeled references: "Section 5", "Article 10", "Clause 3",
    //    "Patient 7", "Chapter 2", "Item 4", "Part III", etc.
    final labelPattern = RegExp(
      r'(?:section|article|clause|chapter|part|item|schedule|patient|record|case|exhibit|paragraph)\s+(\w+)',
      caseSensitive: false,
    );
    for (final m in labelPattern.allMatches(query)) {
      keywords.add(m.group(0)!.toLowerCase());
    }

    // 4. Detect parenthesized proper names like "(Thomas Wright)"
    final parenName = RegExp(r'\(([A-Z][a-z]+ [A-Z][a-z]+)\)').firstMatch(query);
    if (parenName != null) {
      keywords.add(parenName.group(1)!.toLowerCase());
    }

    // 5. Detect quoted phrases "like this" for exact matching
    final quotedPhrases = RegExp(r'"([^"]+)"').allMatches(query);
    for (final m in quotedPhrases) {
      keywords.add(m.group(1)!.toLowerCase());
    }

    return keywords.toList();
  }

  /// Score a chunk against a set of keywords (already expanded).
  double _scoreChunk(String chunkText, List<String> keywords) {
    final lower = chunkText.toLowerCase();
    double score = 0;
    int matchedCount = 0;

    for (final kw in keywords) {
      // For prefix stems: check if any word in text starts with the keyword
      bool matched;
      if (kw.length >= 4 && kw.length <= 6 && !kw.contains(' ')) {
        // Prefix/stem match — find words starting with this stem
        matched = RegExp('\\b${RegExp.escape(kw)}').hasMatch(lower);
      } else {
        matched = lower.contains(kw);
      }
      if (!matched) continue;

      matchedCount++;

      final isBigram = kw.contains(' ');
      final isNumber = RegExp(r'^\d+$').hasMatch(kw);
      final isMoney = kw.contains('\$') || kw.contains('million') ||
          kw.contains('billion') || kw.contains('thousand');
      final isDecimal = RegExp(r'^\d+\.\d+$').hasMatch(kw);

      // Base score: money/decimal worth most (very specific), bigrams high,
      // plain numbers moderate, regular words baseline
      double kwScore = (isMoney || isDecimal)
          ? 4.0
          : isBigram
              ? 3.0
              : (isNumber ? 0.5 : 1.0);

      // Count occurrences
      int count = 0;
      int idx = 0;
      while ((idx = lower.indexOf(kw, idx)) != -1) {
        count++;
        idx += kw.length;
      }
      kwScore += (count - 1) * 0.3;

      // Exact word boundary match bonus
      if (RegExp('\\b${RegExp.escape(kw)}\\b').hasMatch(lower)) {
        kwScore *= 1.3;
      }

      score += kwScore;
    }

    // Bonus for matching a higher fraction of all keywords
    if (score > 0 && keywords.isNotEmpty) {
      score += (matchedCount / keywords.length) * 2.0;
    }

    return score;
  }

  /// Detect if query is broad ("list all", "summarize", "overview", etc.)
  bool _isBroadQuery(String query) {
    final lower = query.toLowerCase();
    return lower.contains('list all') ||
           lower.contains('how many') ||
           lower.contains('summarize') ||
           lower.contains('summary') ||
           lower.contains('overview') ||
           lower.contains('all of') ||
           lower.contains('entire') ||
           lower.contains('everything') ||
           lower.contains('every ') ||
           lower.contains('each ') ||
           lower.contains('enumerate') ||
           lower.contains('complete list') ||
           lower.contains('main points') ||
           lower.contains('key points') ||
           lower.contains('highlight');
  }

  /// Returns up to [limit] chunks whose text matches keywords from [query].
  /// Uses n-gram matching, entity detection, synonym expansion, weighted scoring,
  /// and neighbor retrieval (index-based) to preserve boundary context.
  List<String> searchContext(String query, {int limit = 5}) {
    final rawKeywords = _extractKeywords(query);
    final keywords = _expandKeywords(rawKeywords);
    final broad = _isBroadQuery(query);
    final effectiveLimit = broad ? limit + 3 : limit;

    final all = _box.getAll();
    if (all.isEmpty) return [];

    if (keywords.isEmpty) {
      return all.take(effectiveLimit).map((e) => e.text).toList();
    }

    // Score every chunk
    final scores = <int, double>{};
    for (int i = 0; i < all.length; i++) {
      scores[i] = _scoreChunk(all[i].text, keywords);
    }

    // Rank by score
    final ranked = scores.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    // Collect top hits + their immediate neighbors (index-based, not ID-based)
    final selected = <int>{};
    int added = 0;
    for (final entry in ranked) {
      if (entry.value < 1.0) break;
      if (added >= effectiveLimit) break;
      if (selected.add(entry.key)) added++;
      if (entry.key > 0) selected.add(entry.key - 1);
      if (entry.key < all.length - 1) selected.add(entry.key + 1);
    }

    if (selected.isEmpty) {
      return all.take(effectiveLimit).map((e) => e.text).toList();
    }

    // Cap to effectiveLimit by re-scoring if neighbors pushed us over
    final sorted = selected.toList()..sort();
    if (sorted.length > effectiveLimit) {
      final reScored = sorted.map((i) {
        return MapEntry(scores[i] ?? 0.0, i);
      }).toList()..sort((a, b) => b.key.compareTo(a.key));
      final kept = reScored.take(effectiveLimit).map((e) => e.value).toList()..sort();
      return kept.map((i) => all[i].text).toList();
    }

    return sorted.map((i) => all[i].text).toList();
  }

  /// Total number of stored chunks.
  int get count => _box.count();

  /// Scores ALL chunks against [query] using n-grams, entities, synonyms,
  /// and weighted scoring. For small documents (≤30 chunks).
  /// Also pulls neighbor chunks (before/after top hits) so context that
  /// spans a chunk boundary is never lost.
  List<String> scoredSearchAll(String query, {int limit = 5}) {
    final all = _box.getAll();
    if (all.isEmpty) return [];

    final rawKeywords = _extractKeywords(query);
    final keywords = _expandKeywords(rawKeywords);
    final broad = _isBroadQuery(query);
    final effectiveLimit = broad ? limit + 3 : limit;

    if (keywords.isEmpty) {
      return all.take(effectiveLimit).map((e) => e.text).toList();
    }

    // Score every chunk
    final scores = <int, double>{};
    for (int i = 0; i < all.length; i++) {
      scores[i] = _scoreChunk(all[i].text, keywords);
    }

    // Find top-scoring indices
    final ranked = scores.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    // Collect top hits + their immediate neighbors (for boundary context)
    final selected = <int>{};
    int added = 0;
    for (final entry in ranked) {
      if (entry.value < 1.0) break;
      if (added >= effectiveLimit) break;
      if (selected.add(entry.key)) added++;
      // Pull neighbor before and after so related facts aren't lost
      if (entry.key > 0) selected.add(entry.key - 1);
      if (entry.key < all.length - 1) selected.add(entry.key + 1);
    }

    if (selected.isEmpty) {
      return all.take(effectiveLimit).map((e) => e.text).toList();
    }

    // Return in document order, capped to effectiveLimit
    final sorted = selected.toList()..sort();

    // If neighbors pushed us over the limit, re-score and keep the best
    if (sorted.length > effectiveLimit) {
      final reScored = sorted.map((i) {
        return MapEntry(scores[i] ?? 0.0, i);
      }).toList()..sort((a, b) => b.key.compareTo(a.key));
      final kept = reScored.take(effectiveLimit).map((e) => e.value).toList()..sort();
      return kept.map((i) => all[i].text).toList();
    }

    return sorted.map((i) => all[i].text).toList();
  }

  /// Returns the first [n] chunk texts for preview purposes.
  List<String> getSampleChunks({int n = 3}) {
    return _box.getAll().take(n).map((e) => e.text).toList();
  }

  /// Returns ALL chunk texts in stored order.
  List<String> getAllChunks() {
    return _box.getAll().map((e) => e.text).toList();
  }

  // ───────────────────────────── Lifecycle ────────────────────────────────

  void close() => _store.close();
}
